import {
  ChartArea,
  InfinityIcon,
  RefreshCcw,
  ChartNoAxesColumn,
  Grid2X2,
  Star,
  Zap,
  Facebook,
  Linkedin,
  Twitter,
  Github,
} from "lucide-react";

import { FaFacebook, FaGithub, FaTwitter, FaLinkedinIn, FaTelegram } from "react-icons/fa";

export const navLinks = [
  {
    label: "Why portia.io?",
    href: "/why-portia-io",
  },
  {
    label: "Pricing plans",
    href: "/pricing-plans",
  },
  {
    label: "Resources",
    href: "/resources",
    links: [
      // {
      //   label: "Blogs",
      //   href: "/blogs",
      //   description: "The latest industry news, updates and info.",
      // },
      {
        label: "Faqs",
        href: "/faqs",
        description: "Learn & whatch our client questions and how we answer it .",
      },
      {
        label: "Testimonials",
        href: "/testimonials",
        description: "Learn how our customers are making big changes.",
      },
    ],
  },
  {
    label: "Locations",
    href: "/locations",
  },
  {
    label: "Contact Us",
    href: "/contact-us",
  },
];

export const navbarLinks = [
  {
    icon: Facebook,
    name: "Facebook",
    href: "/",
  },
  {
    icon: Linkedin,
    name: "Linkedin",
    href: "/",
  },
  {
    icon: Twitter,
    name: "Twitter",
    href: "/",
  },
  {
    icon: Github,
    name: "Github",
    href: "/",
  },
];
export const sidebarLinks = [
  {
    name: "Terms",
    href: "/terms",
  },
  {
    name: "Privacy",
    href: "/privacy-policy",
  },
  {
    name: "Licenses",
    href: "/licenses",
  },
];
export const statisticData = [
  {
    value: "40k+",
    name: "Happy Customers",
    description: "We've helped over 40k amazing customers.",
  },
  {
    value: "125+",
    name: "Proxy Locations",
    description: "Switch between proxies quickly to access global content seamlessly.",
  },
  {
    value: "99.9%",
    name: "Uptime",
    description: "Get proxies from different sources, like Portia's mobile network.",
  },
  {
    value: "200+",
    name: "5-star reviews",
    description: "We're proud of our 5-star rating with over 200 reviews.",
  },
];
export const featuresData = [
  {
    icon: InfinityIcon,
    title: "Unlimited Data Usage",
    description: "No Extra Charges Enjoy unlimited data with no hidden fees.",
  },
  {
    icon: RefreshCcw,
    title: "Free Country Switching",
    description: "Switch between multiple countries without additional costs.",
  },
  {
    icon: ChartNoAxesColumn,
    title: "Ip Rotation",
    description: "Change IPs easily with automatic, API, or manual rotation methods.",
  },
  {
    icon: Grid2X2,
    title: "Multi Protocol Support",
    description:
      "Compatible with both HTTPS and SOCKS5 protocols, ensuring adaptability with various software solutions.",
  },
  {
    icon: Star,
    title: "High-Quality, Reliable Proxies",
    description: "Join over 40,000 satisfied clients worldwide.",
  },
  {
    icon: Zap,
    title: "Fast Proxy Speeds",
    description:
      "Enjoy speeds around 15 Mbps with a ping less than 900 ms,perfect for seamless browsing and operations.",
  },
];
export const plansData = [
  {
    price: "15/mth",
    type: "Basic plan",
    features: ["feature 1", "feature 2", "feature 3", "feature 4", "feature 5"],
    isPopular: true,
  },
  {
    price: "30/mth",
    type: "Standard plan",
    features: ["All in Basic plus", "feature 1", "feature 2", "feature 3", "feature 4"],
    isPopular: false,
  },
  {
    price: "40/mth",
    type: "Premium plan",
    features: ["All in Standard plus", "feature 1", "feature 2", "feature 3", "feature 4"],
    isPopular: false,
  },
];
export const faqsData = [
  {
    question: "Is there a any trial available?",
    answer: "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can upgrade to one of our plans.",
  },
  {
    question: "Can I change my plan later?",
    answer: "Yes. It adheres to the WAI-ARIA design pattern.",
  },
  {
    question: "What is your cancellation policy?",
    answer: "Yes. It adheres to the WAI-ARIA design pattern.",
  },
  {
    question: "Can other info be added to an invoice?",
    answer: "Yes. It adheres to the WAI-ARIA design pattern.",
  },
  {
    question: "How dose billing work?",
    answer: "Yes. It adheres to the WAI-ARIA design pattern.",
  },
];
export const footerLinks = [
  {
    title: "Company",
    links: [
      {
        label: "Why portia.io?",
        href: "/why-portia-io",
      },
      {
        label: "Our Plans",
        href: "/our-plans",
      },
      {
        label: "Testimonials",
        href: "/testimonials",
      },
      // {
      // 	label: 'Affiliate program',
      // 	href: '/affiliate-program',
      // },
      {
        label: "Contact us",
        href: "/contact-us",
      },
    ],
  },
  {
    title: "Resources",
    links: [
      // {
      // 	label: 'Blog',
      // 	href: '/blogs',
      // },
      {
        label: "Our Faqs",
        href: "/faqs",
      },
    ],
  },
  // {
  // 	title: 'Social',
  // 	links: [
  // 		{
  // 			label: 'Twitter',
  // 			href: '/',
  // 		},
  // 		{
  // 			label: 'LinkedIn',
  // 			href: '/',
  // 		},
  // 		{
  // 			label: 'Facebook',
  // 			href: '/',
  // 		},
  // 		{
  // 			label: 'Github',
  // 			href: '/',
  // 		},
  // 	],
  // },
  {
    title: "Legal",
    links: [
      {
        label: "Terms",
        href: "/terms",
      },
      {
        label: "Privacy",
        href: "/privacy-policy",
      },
      // {
      // 	label: 'Licenses',
      // 	href: '/licenses',
      // },
    ],
  },
];
export const footerIcons = [
  {
    name: "Twitter",
    icon: FaTwitter,
    href: "/",
  },
  {
    name: "Linkedin",
    icon: FaLinkedinIn,
    href: "/",
  },
  {
    name: "Facebook",
    icon: FaFacebook,
    href: "/",
  },
  {
    name: "Github",
    icon: FaGithub,
    href: "/",
  },
  {
    name: "Telegram",
    icon: FaTelegram,
    href: "/",
  },
];
export const testimonials = [
  {
    rate: 5,
    comment:
      " Portia.io has the best proxies with unmatched IP rotation, speed, and reliability. Essential for social media professionals!",
    name: "Katherine Moss",
    position: "social media manager",
  },
  {
    rate: 2,
    comment:
      "Portia.io has the best proxies with unmatched IP rotation, speed, and reliability. Essential for social media professionals!",
    name: "Jon Doe",
    position: "social media manager",
  },
  {
    rate: 4,
    comment:
      "Portia.io has the best proxies with unmatched IP rotation, speed, and reliability. Essential for social media professionals!",
    name: "Portia Founder",
    position: "social media manager",
  },
];
export const plansData2 = [
  {
    type: "Basic plan",
    status: "Popular",
    price: "$15",
    description: "Basic features for protect browsing usage  with everything you need.",
    features: ["1", "2", "3", "4", "5"],
    message: null,
    isPopular: true,
  },
  {
    type: "Standard plan",
    status: null,
    price: "$30",
    description: "Growing teams up to 20 users.",
    features: ["1", "2", "3", "4", "5"],
    message: "Everything in Basic plus....",
    isPopular: false,
  },
  {
    type: "Premium plan",
    status: null,
    price: "$40",
    description: "Large teams with unlimited users.",
    features: ["1", "2", "3", "4", "5"],
    message: "Everything in Standard plus....",
    isPopular: false,
  },
];
export const countriesData = [
  {
    name: "United States",
    users: "1000,000",
    flagUrl: "/icons/flags/US.svg",
  },
  {
    name: "United Kingdom",
    users: "1000,000",
    flagUrl: "/icons/flags/GB.svg",
  },
  {
    name: "Germany",
    users: "1000,000",
    flagUrl: "/icons/flags/DE.svg",
  },
  {
    name: "Canada",
    users: "1000,000",
    flagUrl: "/icons/flags/CA.svg",
  },
  {
    name: "Italy",
    users: "1000,000",
    flagUrl: "/icons/flags/IT.svg",
  },
  {
    name: "Australia",
    users: "1000,000",
    flagUrl: "/icons/flags/AU.svg",
  },
  {
    name: "Spain",
    users: "1000,000",
    flagUrl: "/icons/flags/ES.svg",
  },
  {
    name: "France",
    users: "1000,000",
    flagUrl: "/icons/flags/FR.svg",
  },
];
export const pricingData = [
  {
    name: "Basic",
    price: "$15",
    isPopular: true,
    description: "Basic features for protect browsing usage  with everything you need.",
    url: "/",
    overview: {
      basic_features: true,
      users: "10",
      Individual_data: "20GB",
      support: true,
      automated_workflows: false,
      integrations: false,
    },
    analytics: {
      analytics: "Basic",
      export_reports: true,
      scheduled_reports: true,
      API_access: false,
      advanced_reports: false,
      saved_reports: false,
      customer_properties: false,
      custom_fields: false,
    },
    user_access: {
      sso_saml: true,
      advanced_permissions: false,
      audit_log: false,
      data_history: false,
    },
  },
  {
    name: "Standard",
    price: "$30",
    isPopular: false,
    description: "based  on features we can tell this is perfect for them ?",
    url: "/",
    overview: {
      basic_features: true,
      users: "20",
      Individual_data: "40GB",
      support: true,
      automated_workflows: true,
      integrations: true,
    },
    analytics: {
      analytics: "Advanced",
      export_reports: true,
      scheduled_reports: true,
      API_access: true,
      advanced_reports: true,
      saved_reports: true,
      customer_properties: false,
      custom_fields: false,
    },
    user_access: {
      sso_saml: true,
      advanced_permissions: true,
      audit_log: false,
      data_history: false,
    },
  },
  {
    name: "Premium",
    price: "$40",
    isPopular: false,
    description: "Personalized service and enterprise security for large teams.",
    url: "/",
    overview: {
      basic_features: true,
      users: "Unlimited",
      Individual_data: "Unlimited",
      support: true,
      automated_workflows: true,
      integrations: true,
    },
    analytics: {
      analytics: "Advanced",
      export_reports: true,
      scheduled_reports: true,
      API_access: true,
      advanced_reports: true,
      saved_reports: true,
      customer_properties: true,
      custom_fields: true,
    },
    user_access: {
      sso_saml: true,
      advanced_permissions: true,
      audit_log: true,
      data_history: true,
    },
  },
];
export const basicPlan = {
  name: "Basic",
  price: "$15",
  isPopular: true,
  description: "Basic features for protect browsing usage  with everything you need.",
  overview: {
    basic_features: true,
    users: "10",
    Individual_data: "20GB",
    support: true,
    automated_workflows: false,
    integrations: false,
  },
  analytics: {
    analytics: "Basic",
    export_reports: true,
    scheduled_reports: true,
    API_access: false,
    advanced_reports: false,
    saved_reports: false,
    customer_properties: false,
    custom_fields: false,
  },
  user_access: {
    sso_saml: true,
    advanced_permissions: false,
    audit_log: false,
    data_history: false,
  },
};
export const standardPlan = {
  name: "Standard",
  price: "$30",
  isPopular: false,
  description: "based  on features we can tell this is perfect for them ?",
  overview: {
    basic_features: true,
    users: "20",
    Individual_data: "40GB",
    support: true,
    automated_workflows: true,
    integrations: true,
  },
  analytics: {
    analytics: "Advanced",
    export_reports: true,
    scheduled_reports: true,
    API_access: true,
    advanced_reports: true,
    saved_reports: true,
    customer_properties: false,
    custom_fields: false,
  },
  user_access: {
    sso_saml: true,
    advanced_permissions: true,
    audit_log: false,
    data_history: false,
  },
};
export const premiumPlan = {
  name: "Premium",
  price: "$40",
  isPopular: false,
  description: "Personalized service and enterprise security for large teams.",
  overview: {
    basic_features: true,
    users: "Unlimited",
    Individual_data: "Unlimited",
    support: true,
    automated_workflows: true,
    integrations: true,
  },
  analytics: {
    analytics: "Advanced",
    export_reports: true,
    scheduled_reports: true,
    API_access: true,
    advanced_reports: true,
    saved_reports: true,
    customer_properties: true,
    custom_fields: true,
  },
  user_access: {
    sso_saml: true,
    advanced_permissions: true,
    audit_log: true,
    data_history: true,
  },
};
export const customersData = [
  {
    rate: 5,
    name: "Alisa Hester",
    position: "PM, Hourglass",
    agency: "Web Design Agency",
    comment: "“We’ve really sped up our workflow using Untitled.”",
    imgUrl: "/images/users/user1.png",
  },
  {
    rate: 5,
    name: "Rich Wilson",
    position: "COO, Command+R",
    agency: "Web Development Agency",
    comment: "“We’ve really sped up our workflow using Untitled.”",
    imgUrl: "/images/users/user2.png",
  },

  {
    rate: 5,
    name: "Johnny Bell",
    position: "PM, Sisyphus",
    agency: "Machine Learning",
    comment: "“We’ve really sped up our workflow using Untitled.”",
    imgUrl: "/images/users/user3.png",
  },
  {
    rate: 5,
    name: "Annie Stanley",
    position: "Designer, Catalog",
    agency: "UX Agency",
    comment: "“We’ve really sped up our workflow using Untitled.”",
    imgUrl: "/images/users/user4.png",
  },
];
export const blogsData = [
  {
    id: "1",
    published: "20 Jan 2022",
    title: "UX review presentations",
    url: "/",
    description: "How do you create compelling presentations that wow your colleagues and impress your managers?",
    categories: ["Design", "Research", "Presentation"],
    imgUrl: "/images/blogs/blog (1).jpg",
    isFavorite: true,
    order: 1,
  },
  {
    id: "2",
    published: "19 Jan 2022",
    title: "Migrating to Linear 101",
    url: "/",
    description: "Linear helps streamline software projects, sprints, tasks, and bug tracking. Here’s how to get...",
    categories: ["Design", "Research"],
    imgUrl: "/images/blogs/blog (2).jpg",
    isFavorite: true,
    order: 2,
  },
  {
    id: "3",
    published: "18 Jan 2022",
    title: "Building your API Stack",
    url: "/",
    description: "The rise of RESTful APIs has been met by a rise in tools for creating, testing, and manag...",
    categories: ["Design", "Research"],
    imgUrl: "/images/blogs/blog (3).jpg",
    isFavorite: true,
    order: 3,
  },
  {
    id: "4",
    published: "17 Jan 2022",
    title: "Bill Walsh leadership lessons",
    url: "/",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    categories: ["Leadership", "Management"],
    imgUrl: "/images/blogs/blog (4).jpg",
    isFavorite: false,
    order: 4,
  },
  {
    id: "5",
    published: "16 Jan 2022",
    title: "PM mental models",
    url: "/",
    description: "Mental models are simple expressions of complex processes or relationships.",
    categories: ["Product", "Research", "Frameworks"],
    imgUrl: "/images/blogs/blog (5).jpg",
    isFavorite: false,
    order: 5,
  },
  {
    id: "6",
    published: "15 Jan 2022",
    title: "What is Wireframing?",
    url: "/",
    description: "Introduction to Wireframing and its Principles. Learn from the best in the industry.",
    categories: ["Design", "Research"],
    imgUrl: "/images/blogs/blog (6).jpg",
    isFavorite: false,
    order: 6,
  },
  {
    id: "7",
    published: "14 Jan 2022",
    title: "How collaboration makes us better designers",
    url: "/",
    description: "Collaboration can make our teams stronger, and our individual designs better.",
    categories: ["Design", "Research"],
    imgUrl: "/images/blogs/blog (7).jpg",
    isFavorite: false,
    order: 7,
  },
  {
    id: "8",
    published: "13 Jan 2022",
    title: "Our top 10 Javascript frameworks to use",
    url: "/",
    description: "JavaScript frameworks make development easy with extensive features and functionalities.",
    categories: ["Software Development", "Tools", "SaaS"],
    imgUrl: "/images/blogs/blog (8).jpg",
    isFavorite: false,
    order: 8,
  },
  {
    id: "9",
    published: "12 Jan 2022",
    title: "Podcast: Creating a better CX Community",
    url: "/",
    description: "Starting a community doesn’t need to be complicated, but how do you get started?",
    categories: ["Podcasts", "Customer Success"],
    imgUrl: "/images/blogs/blog (9).jpg",
    isFavorite: false,
    order: 9,
  },
];

export const freqAQsData = [
  {
    question: "Is there a any  trial available?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
  {
    question: "Can I change my plan later?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
  {
    question: "How many accounts can I run on a single proxy?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
  {
    question: "Which sites can I access with your proxies?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
  {
    question: "Do you have any blocked sites?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
  {
    question: "What is the uptime of your proxies?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
  {
    question: "What proxy protocols are you supporting?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
  {
    question: "Can I use your proxies on social networks?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
  {
    question: "Do you have an affiliation program?",
    answer:
      "Yes, you can try us for only 0.25$ for 2 hours. and then if you want you can sub scrip in one of our plans ",
  },
];

export const countriesName = [
  { label: "US", value: "US" },
  { label: "SY", value: "SY" },
  { label: "DE", value: "DE" },
  { label: "AF", value: "AF" },
  { label: "AL", value: "AL" },
  { label: "AR", value: "AR" },
  { label: "AT", value: "AT" },
  { label: "AU", value: "AU" },
  { label: "AZ", value: "AZ" },
  { label: "BA", value: "BA" },
  { label: "BD", value: "BD" },
  { label: "BE", value: "BE" },
  { label: "BG", value: "BG" },
  { label: "BR", value: "BR" },
  { label: "CA", value: "CA" },
  { label: "CH", value: "CH" },
  { label: "CL", value: "CL" },
  { label: "CN", value: "CN" },
  { label: "CO", value: "CO" },
  { label: "CR", value: "CR" },
  { label: "CY", value: "CY" },
  { label: "CZ", value: "CZ" },
  { label: "DK", value: "DK" },
  { label: "EE", value: "EE" },
  { label: "ES", value: "ES" },
  { label: "FI", value: "FI" },
  { label: "FR", value: "FR" },
  { label: "GR", value: "GR" },
  { label: "HK", value: "HK" },
  { label: "HR", value: "HR" },
  { label: "HU", value: "HU" },
  { label: "ID", value: "ID" },
  { label: "IE", value: "IE" },
  { label: "IL", value: "IL" },
  { label: "IN", value: "IN" },
  { label: "IT", value: "IT" },
  { label: "JP", value: "JP" },
  { label: "KR", value: "KR" },
  { label: "LT", value: "LT" },
  { label: "LU", value: "LU" },
  { label: "MX", value: "MX" },
  { label: "MY", value: "MY" },
  { label: "NL", value: "NL" },
  { label: "NO", value: "NO" },
  { label: "NZ", value: "NZ" },
  { label: "PH", value: "PH" },
  { label: "PL", value: "PL" },
  { label: "PT", value: "PT" },
  { label: "RU", value: "RU" },
  { label: "SE", value: "SE" },
  { label: "SG", value: "SG" },
  { label: "TH", value: "TH" },
  { label: "TR", value: "TR" },
];

export const data = [
  {
    id: 1,
    amount: 2,
    cost: "2.00",
    is_top: false,
    plan: {
      id: 1,
      name: "Hourly",
    },
    package: {
      id: 21,
      name: "Basic",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ullam error ab?",
      created_at: "2024-09-30T18:11:16.000000Z",
      updated_at: "2024-09-30T18:11:16.000000Z",
      feature_groups: [
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
      ],
    },
    created_at: "2024-09-30T18:11:18.000000Z",
    updated_at: "2024-09-30T18:11:18.000000Z",
  },
  {
    id: 1,
    amount: 2,
    cost: "2.00",
    is_top: false,
    plan: {
      id: 1,
      name: "Hourly",
    },
    package: {
      id: 21,
      name: "Basic",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ullam error ab?",
      created_at: "2024-09-30T18:11:16.000000Z",
      updated_at: "2024-09-30T18:11:16.000000Z",
      feature_groups: [
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
      ],
    },
    created_at: "2024-09-30T18:11:18.000000Z",
    updated_at: "2024-09-30T18:11:18.000000Z",
  },
  {
    id: 1,
    amount: 2,
    cost: "2.00",
    is_top: false,
    plan: {
      id: 1,
      name: "Hourly",
    },
    package: {
      id: 21,
      name: "Basic",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ullam error ab?",
      created_at: "2024-09-30T18:11:16.000000Z",
      updated_at: "2024-09-30T18:11:16.000000Z",
      feature_groups: [
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
        {
          id: 96,
          name: "overview",
          package_id: 21,
          created_at: "2024-09-30T18:11:17.000000Z",
          updated_at: "2024-09-30T18:11:17.000000Z",
          features: [
            {
              id: 261,
              feature_group_id: 96,
              name: "basic feature",
              description: "Dolores minima corporis blanditiis vel qui magni.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 262,
              feature_group_id: 96,
              name: "users",
              description: "Eos pariatur nulla sed illum similique.",
              value: "10, 20, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 263,
              feature_group_id: 96,
              name: "individual data",
              description: "Provident est ratione nihil porro.",
              value: "20GB, 40GB, Unlimited",
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 264,
              feature_group_id: 96,
              name: "support",
              description: "Impedit et et et doloremque doloribus.",
              value: true,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 265,
              feature_group_id: 96,
              name: "automated workflows",
              description: "Automated workflows description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
            {
              id: 266,
              feature_group_id: 96,
              name: "200+ integrations",
              description: "200+ integrations description.",
              value: false,
              created_at: "2024-09-30T18:11:17.000000Z",
              updated_at: "2024-09-30T18:11:17.000000Z",
            },
          ],
        },
      ],
    },
    created_at: "2024-09-30T18:11:18.000000Z",
    updated_at: "2024-09-30T18:11:18.000000Z",
  },
];

export const overviewData = [
  {
    title: "Paid Proxies",
    content: "12 Proxies",
    label: "View all proxies",
    href: "/dashboard/my-proxies",
    fill: "default",
    theme: "default",
    icon: Zap,
  },
  {
    title: "User Balance",
    content: "100$",
    label: "View all deposit",
    href: "/dashboard/deposits",
    fill: "success",
    theme: "success",
    icon: ChartArea,
  },
];

export const overviewTableData = [
  {
    id: "1",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "8080",
    expiredData: "2024-12-01",
    isExpired: false,
    usernamePassword: "user1:pass1",
  },
  {
    id: "2",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Yearly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-08-01",
    isExpired: true,
    usernamePassword: "user2:pass2",
  },
  {
    id: "3",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Weekly",
    type: "Residential",
    network: "3G",
    port: "7070",
    expiredData: "2024-09-15",
    isExpired: false,
    usernamePassword: "user3:pass3",
  },
  {
    id: "4",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-01-20",
    isExpired: false,
    usernamePassword: "user4:pass4",
  },
  {
    id: "5",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-01",
    isExpired: false,
    usernamePassword: "user5:pass5",
  },
  {
    id: "6",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "5050",
    expiredData: "2025-05-01",
    isExpired: false,
    usernamePassword: "user6:pass6",
  },
  {
    id: "7",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-09-21",
    isExpired: true,
    usernamePassword: "user7:pass7",
  },
  {
    id: "8",
    renew: false,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "3G",
    port: "2020",
    expiredData: "2024-11-01",
    isExpired: true,
    usernamePassword: "user8:pass8",
  },
  {
    id: "9",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-12-15",
    isExpired: false,
    usernamePassword: "user9:pass9",
  },
  {
    id: "10",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "7070",
    expiredData: "2024-10-05",
    isExpired: true,
    usernamePassword: "user10:pass10",
  },
  {
    id: "11",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-04-01",
    isExpired: false,
    usernamePassword: "user11:pass11",
  },
  {
    id: "12",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-15",
    isExpired: false,
    usernamePassword: "user12:pass12",
  },
  {
    id: "13",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-21",
    isExpired: false,
    usernamePassword: "user13:pass13",
  },
  {
    id: "14",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Yearly",
    type: "Residential",
    network: "3G",
    port: "3030",
    expiredData: "2025-06-01",
    isExpired: true,
    usernamePassword: "user14:pass14",
  },
  {
    id: "15",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "2020",
    expiredData: "2024-12-05",
    isExpired: false,
    usernamePassword: "user15:pass15",
  },
  {
    id: "16",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-09-30",
    isExpired: false,
    usernamePassword: "user16:pass16",
  },
  {
    id: "17",
    renew: false,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "9090",
    expiredData: "2025-02-15",
    isExpired: true,
    usernamePassword: "user17:pass17",
  },
  {
    id: "18",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "7070",
    expiredData: "2024-11-10",
    isExpired: false,
    usernamePassword: "user18:pass18",
  },
  {
    id: "19",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "6060",
    expiredData: "2024-10-25",
    isExpired: false,
    usernamePassword: "user19:pass19",
  },
  {
    id: "20",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-30",
    isExpired: true,
    usernamePassword: "user20:pass20",
  },
  {
    id: "21",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2025-05-10",
    isExpired: false,
    usernamePassword: "user21:pass21",
  },
  {
    id: "22",
    renew: false,
    status: false,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-12-20",
    isExpired: true,
    usernamePassword: "user22:pass22",
  },
  {
    id: "23",
    renew: true,
    status: true,
    package: "Basic",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "2020",
    expiredData: "2024-09-05",
    isExpired: false,
    usernamePassword: "user23:pass23",
  },
  {
    id: "24",
    renew: true,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-11-21",
    isExpired: true,
    usernamePassword: "user24:pass24",
  },
  {
    id: "25",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "9090",
    expiredData: "2025-06-01",
    isExpired: false,
    usernamePassword: "user25:pass25",
  },
  {
    id: "26",
    renew: false,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "7070",
    expiredData: "2024-10-11",
    isExpired: false,
    usernamePassword: "user26:pass26",
  },
  {
    id: "27",
    renew: true,
    status: false,
    package: "Basic",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2024-11-15",
    isExpired: true,
    usernamePassword: "user27:pass27",
  },
  {
    id: "28",
    renew: false,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "5050",
    expiredData: "2025-03-01",
    isExpired: false,
    usernamePassword: "user28:pass28",
  },
  {
    id: "29",
    renew: true,
    status: false,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "4040",
    expiredData: "2024-10-30",
    isExpired: false,
    usernamePassword: "user29:pass29",
  },
  {
    id: "30",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "3030",
    expiredData: "2024-12-10",
    isExpired: true,
    usernamePassword: "user30:pass30",
  },
];

export const proxiesData = [
  {
    title: "My Active Proxies",
    content: "12 Proxies",
    fill: "success",
    theme: "success",
    icon: Zap,
  },
  {
    title: "My Expired Proxies",
    content: "15 Proxies",
    fill: "alert",
    theme: "alert",
    icon: Zap,
  },
  {
    title: "All Proxies",
    content: "27 Proxies",
    fill: "secondary",
    theme: "secondary",
    icon: Zap,
  },
];

export const proxiesTableData = [
  {
    id: "1",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "8080",
    expiredData: "2024-12-01",
    isExpired: false,
    usernamePassword: "user1:pass1",
  },
  {
    id: "2",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Yearly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-08-01",
    isExpired: true,
    usernamePassword: "user2:pass2",
  },
  {
    id: "3",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Weekly",
    type: "Residential",
    network: "3G",
    port: "7070",
    expiredData: "2024-09-15",
    isExpired: false,
    usernamePassword: "user3:pass3",
  },
  {
    id: "4",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-01-20",
    isExpired: false,
    usernamePassword: "user4:pass4",
  },
  {
    id: "5",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-01",
    isExpired: false,
    usernamePassword: "user5:pass5",
  },
  {
    id: "6",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "5050",
    expiredData: "2025-05-01",
    isExpired: false,
    usernamePassword: "user6:pass6",
  },
  {
    id: "7",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-09-21",
    isExpired: true,
    usernamePassword: "user7:pass7",
  },
  {
    id: "8",
    renew: false,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "3G",
    port: "2020",
    expiredData: "2024-11-01",
    isExpired: true,
    usernamePassword: "user8:pass8",
  },
  {
    id: "9",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-12-15",
    isExpired: false,
    usernamePassword: "user9:pass9",
  },
  {
    id: "10",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "7070",
    expiredData: "2024-10-05",
    isExpired: true,
    usernamePassword: "user10:pass10",
  },
  {
    id: "11",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-04-01",
    isExpired: false,
    usernamePassword: "user11:pass11",
  },
  {
    id: "12",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-15",
    isExpired: false,
    usernamePassword: "user12:pass12",
  },
  {
    id: "13",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-21",
    isExpired: false,
    usernamePassword: "user13:pass13",
  },
  {
    id: "14",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Yearly",
    type: "Residential",
    network: "3G",
    port: "3030",
    expiredData: "2025-06-01",
    isExpired: true,
    usernamePassword: "user14:pass14",
  },
  {
    id: "15",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "2020",
    expiredData: "2024-12-05",
    isExpired: false,
    usernamePassword: "user15:pass15",
  },
  {
    id: "16",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-09-30",
    isExpired: false,
    usernamePassword: "user16:pass16",
  },
  {
    id: "17",
    renew: false,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "9090",
    expiredData: "2025-02-15",
    isExpired: true,
    usernamePassword: "user17:pass17",
  },
  {
    id: "18",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "7070",
    expiredData: "2024-11-10",
    isExpired: false,
    usernamePassword: "user18:pass18",
  },
  {
    id: "19",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "6060",
    expiredData: "2024-10-25",
    isExpired: false,
    usernamePassword: "user19:pass19",
  },
  {
    id: "20",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-30",
    isExpired: true,
    usernamePassword: "user20:pass20",
  },
  {
    id: "21",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2025-05-10",
    isExpired: false,
    usernamePassword: "user21:pass21",
  },
  {
    id: "22",
    renew: false,
    status: false,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-12-20",
    isExpired: true,
    usernamePassword: "user22:pass22",
  },
  {
    id: "23",
    renew: true,
    status: true,
    package: "Basic",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "2020",
    expiredData: "2024-09-05",
    isExpired: false,
    usernamePassword: "user23:pass23",
  },
  {
    id: "24",
    renew: true,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-11-21",
    isExpired: true,
    usernamePassword: "user24:pass24",
  },
  {
    id: "25",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "9090",
    expiredData: "2025-06-01",
    isExpired: false,
    usernamePassword: "user25:pass25",
  },
  {
    id: "26",
    renew: false,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "7070",
    expiredData: "2024-10-11",
    isExpired: false,
    usernamePassword: "user26:pass26",
  },
  {
    id: "27",
    renew: true,
    status: false,
    package: "Basic",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2024-11-15",
    isExpired: true,
    usernamePassword: "user27:pass27",
  },
  {
    id: "28",
    renew: false,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "5050",
    expiredData: "2025-03-01",
    isExpired: false,
    usernamePassword: "user28:pass28",
  },
  {
    id: "29",
    renew: true,
    status: false,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "4040",
    expiredData: "2024-10-30",
    isExpired: false,
    usernamePassword: "user29:pass29",
  },
  {
    id: "30",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "3030",
    expiredData: "2024-12-10",
    isExpired: true,
    usernamePassword: "user30:pass30",
  },
];

export const depositsData = [
  {
    title: "This Month",
    price: "0.00$",
    color: "#26a6a4",
    data: [
      { id: 1, amount: 20 },
      { id: 2, amount: 30 },
      { id: 3, amount: 70 },
      { id: 4, amount: 45 },
      { id: 5, amount: 50 },
    ],
  },
  {
    title: "This Year",
    price: "0.00$",
    color: "#f63d68",
    data: [
      { id: 1, amount: 150 },
      { id: 2, amount: 320 },
      { id: 3, amount: 710 },
      { id: 4, amount: 415 },
      { id: 5, amount: 820 },
    ],
  },
  {
    title: "All Time",
    price: "0.00$",
    color: "#7a5af8",
    data: [
      { id: 1, amount: 2000 },
      { id: 2, amount: 3012 },
      { id: 3, amount: 7460 },
      { id: 4, amount: 4512 },
      { id: 5, amount: 8046 },
    ],
  },
];

export const depositsTableData = [
  {
    id: 1,
    amount: "25.00 USDT",
    date: "Jan 4, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 2,
    amount: "50.00 USDT",
    date: "Jan 4, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 3,
    amount: "120.00 USDT",
    date: "Jan 2, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 4,
    amount: "125.00 USDT",
    date: "Jan 6, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 5,
    amount: "130.00 USDT",
    date: "Jan 8, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 6,
    amount: "75.00 USDT",
    date: "Jan 6, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 7,
    amount: "500.00 USDT",
    date: "Jan 4, 2022",
    typeOfPayment: "Payeer",
  },

  {
    id: 8,
    amount: "60.00 USDT",
    date: "Feb 1, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 9,
    amount: "110.00 USDT",
    date: "Feb 2, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 10,
    amount: "95.00 USDT",
    date: "Feb 5, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 11,
    amount: "200.00 USDT",
    date: "Feb 6, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 12,
    amount: "175.00 USDT",
    date: "Feb 8, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 13,
    amount: "80.00 USDT",
    date: "Feb 10, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 14,
    amount: "400.00 USDT",
    date: "Feb 14, 2022",
    typeOfPayment: "Crypto",
  },

  {
    id: 15,
    amount: "300.00 USDT",
    date: "Mar 1, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 16,
    amount: "250.00 USDT",
    date: "Mar 3, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 17,
    amount: "150.00 USDT",
    date: "Mar 5, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 18,
    amount: "450.00 USDT",
    date: "Mar 6, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 19,
    amount: "225.00 USDT",
    date: "Mar 8, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 20,
    amount: "135.00 USDT",
    date: "Mar 10, 2022",
    typeOfPayment: "Payeer",
  },

  {
    id: 21,
    amount: "500.00 USDT",
    date: "Apr 1, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 22,
    amount: "600.00 USDT",
    date: "Apr 2, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 23,
    amount: "350.00 USDT",
    date: "Apr 5, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 24,
    amount: "750.00 USDT",
    date: "Apr 6, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 25,
    amount: "275.00 USDT",
    date: "Apr 8, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 26,
    amount: "150.00 USDT",
    date: "Apr 10, 2022",
    typeOfPayment: "Payeer",
  },

  {
    id: 27,
    amount: "450.00 USDT",
    date: "May 1, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 28,
    amount: "300.00 USDT",
    date: "May 2, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 29,
    amount: "225.00 USDT",
    date: "May 5, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 30,
    amount: "700.00 USDT",
    date: "May 6, 2022",
    typeOfPayment: "Crypto",
  },
];
