declare type ProxyColumn = {
  sequence: string;
  id: number;
  re_new: number;
  is_active: number;
  package_name: string;
  city_name: string;
  protocol: string;
  service_provider: string;
  protocol_port: number;
  expire_at: string;
  username: string;
  password: string;
  plan_name: string;
  proxy_id: string;
  parent_proxy_id: string;
  package_id: string;
  duration: number;
  ip_addr: any;
};
declare type Proxy = {
  sequence: string;
  id: number;
  re_new: number;
  is_active: number;
  package_name: string;
  protocol: string;
  service_provider: string;
  protocol_port: number;
  expire_at: string;
  username: string;
  password: string;
  plan_name: string;
  proxy_id: string;
  parent_proxy_id: string;
  package_id: string;
  duration: number;
  ip_addr: any;
  amount: any;
  rotation_time: any;
  country_name: any;
};
