import React from "react";

import { columns, Location } from "./columns";
import { DataTable } from "./data-table";

async function getData(): Promise<Location[]> {
  return [
    {
      id: "1",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "2",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "3",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "4",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "5",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "6",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "7",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "8",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "9",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "10",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "11",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "12",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: false,
    },
    {
      id: "13",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "14",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "1",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "2",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "3",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "4",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "5",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "6",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "7",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "8",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "9",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "10",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "11",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "12",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: false,
    },
    {
      id: "13",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "14",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "1",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "2",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "3",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "4",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "5",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "6",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "7",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "8",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "9",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "10",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "11",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "12",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: false,
    },
    {
      id: "13",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "14",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "1",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "2",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "3",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "4",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "5",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "6",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "7",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "8",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "9",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "10",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "11",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "12",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: false,
    },
    {
      id: "13",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "14",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "1",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "2",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "3",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "4",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "5",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "6",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "7",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "8",
      country: "USA",
      state: "NY",
      isp: "O2/READING",
      ipRotation: "5 min",
      connect: true,
    },
    {
      id: "9",
      country: "USA",
      state: "California",
      isp: "VODAFONE/FARNBOROUGH",
      ipRotation: "30 min",
      connect: false,
    },
    {
      id: "10",
      country: "Germany",
      state: "Berlin",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: true,
    },
    {
      id: "11",
      country: "France",
      state: "Paris",
      isp: "THREE/SHEFFIELD",
      ipRotation: "1 hour",
      connect: true,
    },
    {
      id: "12",
      country: "USA",
      state: "NY",
      isp: "THREE/SHEFFIELD",
      ipRotation: "15 min",
      connect: false,
    },
    {
      id: "13",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
    {
      id: "14",
      country: "Canada",
      state: "Arizona",
      isp: "THREE/SHEFFIELD",
      ipRotation: "30 min",
      connect: true,
    },
  ];
}

export const LocationClient = async () => {
  const data = await getData();

  return (
    <>
      <div className="w-full space-y-3 text-center lg:text-left">
        <p className="text-gray-primary text-lg">
          Our Available Proxy’s Locations
        </p>
        <h3 className="text-2xl lg:text-3xl font-semibold">
          Choose your location’s needs
        </h3>
        <p className="text-gray-primary text-lg">
          you can easily filter your results based on country, state, isp,
          rotation by this:
        </p>
      </div>
      <DataTable columns={columns} data={data} />
    </>
  );
};
