import { ChartArea, Zap } from "lucide-react";

export const routes = [
  {
    label: "Dashboard",
    href: "/dashboard",
  },
  {
    label: "My Proxies",
    href: "/dashboard/my-proxies",
  },
  {
    label: "Pricing Plans",
    href: "/dashboard/pricing-plans",
  },
  {
    label: "Deposits",
    href: "/dashboard/deposits",
  },
];

export const overviewData = [
  {
    title: "Paid Proxies",
    content: "12 Proxies",
    label: "View all proxies",
    href: "/dashboard/my-proxies",
    fill: "default",
    theme: "default",
    icon: Zap,
  },
  {
    title: "User Balance",
    content: "100$",
    label: "View all deposit",
    href: "/dashboard/deposit",
    fill: "success",
    theme: "success",
    icon: ChartArea,
  },
];

export const overviewTableData = [
  {
    id: "1",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "8080",
    expiredData: "2024-12-01",
    isExpired: false,
    usernamePassword: "user1:pass1",
  },
  {
    id: "2",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Yearly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-08-01",
    isExpired: true,
    usernamePassword: "user2:pass2",
  },
  {
    id: "3",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Weekly",
    type: "Residential",
    network: "3G",
    port: "7070",
    expiredData: "2024-09-15",
    isExpired: false,
    usernamePassword: "user3:pass3",
  },
  {
    id: "4",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-01-20",
    isExpired: false,
    usernamePassword: "user4:pass4",
  },
  {
    id: "5",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-01",
    isExpired: false,
    usernamePassword: "user5:pass5",
  },
  {
    id: "6",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "5050",
    expiredData: "2025-05-01",
    isExpired: false,
    usernamePassword: "user6:pass6",
  },
  {
    id: "7",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-09-21",
    isExpired: true,
    usernamePassword: "user7:pass7",
  },
  {
    id: "8",
    renew: false,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "3G",
    port: "2020",
    expiredData: "2024-11-01",
    isExpired: true,
    usernamePassword: "user8:pass8",
  },
  {
    id: "9",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-12-15",
    isExpired: false,
    usernamePassword: "user9:pass9",
  },
  {
    id: "10",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "7070",
    expiredData: "2024-10-05",
    isExpired: true,
    usernamePassword: "user10:pass10",
  },
  {
    id: "11",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-04-01",
    isExpired: false,
    usernamePassword: "user11:pass11",
  },
  {
    id: "12",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-15",
    isExpired: false,
    usernamePassword: "user12:pass12",
  },
  {
    id: "13",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-21",
    isExpired: false,
    usernamePassword: "user13:pass13",
  },
  {
    id: "14",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Yearly",
    type: "Residential",
    network: "3G",
    port: "3030",
    expiredData: "2025-06-01",
    isExpired: true,
    usernamePassword: "user14:pass14",
  },
  {
    id: "15",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "2020",
    expiredData: "2024-12-05",
    isExpired: false,
    usernamePassword: "user15:pass15",
  },
  {
    id: "16",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-09-30",
    isExpired: false,
    usernamePassword: "user16:pass16",
  },
  {
    id: "17",
    renew: false,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "9090",
    expiredData: "2025-02-15",
    isExpired: true,
    usernamePassword: "user17:pass17",
  },
  {
    id: "18",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "7070",
    expiredData: "2024-11-10",
    isExpired: false,
    usernamePassword: "user18:pass18",
  },
  {
    id: "19",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "6060",
    expiredData: "2024-10-25",
    isExpired: false,
    usernamePassword: "user19:pass19",
  },
  {
    id: "20",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-30",
    isExpired: true,
    usernamePassword: "user20:pass20",
  },
  {
    id: "21",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2025-05-10",
    isExpired: false,
    usernamePassword: "user21:pass21",
  },
  {
    id: "22",
    renew: false,
    status: false,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-12-20",
    isExpired: true,
    usernamePassword: "user22:pass22",
  },
  {
    id: "23",
    renew: true,
    status: true,
    package: "Basic",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "2020",
    expiredData: "2024-09-05",
    isExpired: false,
    usernamePassword: "user23:pass23",
  },
  {
    id: "24",
    renew: true,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-11-21",
    isExpired: true,
    usernamePassword: "user24:pass24",
  },
  {
    id: "25",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "9090",
    expiredData: "2025-06-01",
    isExpired: false,
    usernamePassword: "user25:pass25",
  },
  {
    id: "26",
    renew: false,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "7070",
    expiredData: "2024-10-11",
    isExpired: false,
    usernamePassword: "user26:pass26",
  },
  {
    id: "27",
    renew: true,
    status: false,
    package: "Basic",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2024-11-15",
    isExpired: true,
    usernamePassword: "user27:pass27",
  },
  {
    id: "28",
    renew: false,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "5050",
    expiredData: "2025-03-01",
    isExpired: false,
    usernamePassword: "user28:pass28",
  },
  {
    id: "29",
    renew: true,
    status: false,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "4040",
    expiredData: "2024-10-30",
    isExpired: false,
    usernamePassword: "user29:pass29",
  },
  {
    id: "30",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "3030",
    expiredData: "2024-12-10",
    isExpired: true,
    usernamePassword: "user30:pass30",
  },
];
