import { ChartArea, Zap } from "lucide-react";

export const routes = [
  {
    label: "Dashboard",
    href: "/dashboard",
  },
  {
    label: "My Proxies",
    href: "/dashboard/my-proxies",
  },
  {
    label: "Pricing Plans",
    href: "/dashboard/pricing-plans",
  },
  {
    label: "Deposits",
    href: "/dashboard/deposits",
  },
] as const;

export const overviewData = [
  {
    title: "Paid Proxies",
    content: "12 Proxies",
    label: "View all proxies",
    href: "/dashboard/my-proxies",
    fill: "default",
    theme: "default",
    icon: Zap,
  },
  {
    title: "User Balance",
    content: "100$",
    label: "View all deposit",
    href: "/dashboard/deposit",
    fill: "success",
    theme: "success",
    icon: ChartArea,
  },
] as const;

export const overviewTableData = [
  {
    id: "1",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "8080",
    expiredData: "2024-12-01",
    isExpired: false,
    usernamePassword: "user1:pass1",
  },
  {
    id: "2",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Yearly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-08-01",
    isExpired: true,
    usernamePassword: "user2:pass2",
  },
  {
    id: "3",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Weekly",
    type: "Residential",
    network: "3G",
    port: "7070",
    expiredData: "2024-09-15",
    isExpired: false,
    usernamePassword: "user3:pass3",
  },
  {
    id: "4",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-01-20",
    isExpired: false,
    usernamePassword: "user4:pass4",
  },
  {
    id: "5",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-01",
    isExpired: false,
    usernamePassword: "user5:pass5",
  },
  {
    id: "6",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "5050",
    expiredData: "2025-05-01",
    isExpired: false,
    usernamePassword: "user6:pass6",
  },
  {
    id: "7",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-09-21",
    isExpired: true,
    usernamePassword: "user7:pass7",
  },
  {
    id: "8",
    renew: false,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "3G",
    port: "2020",
    expiredData: "2024-11-01",
    isExpired: true,
    usernamePassword: "user8:pass8",
  },
  {
    id: "9",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-12-15",
    isExpired: false,
    usernamePassword: "user9:pass9",
  },
  {
    id: "10",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "7070",
    expiredData: "2024-10-05",
    isExpired: true,
    usernamePassword: "user10:pass10",
  },
  {
    id: "11",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-04-01",
    isExpired: false,
    usernamePassword: "user11:pass11",
  },
  {
    id: "12",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-15",
    isExpired: false,
    usernamePassword: "user12:pass12",
  },
  {
    id: "13",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-21",
    isExpired: false,
    usernamePassword: "user13:pass13",
  },
  {
    id: "14",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Yearly",
    type: "Residential",
    network: "3G",
    port: "3030",
    expiredData: "2025-06-01",
    isExpired: true,
    usernamePassword: "user14:pass14",
  },
  {
    id: "15",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "2020",
    expiredData: "2024-12-05",
    isExpired: false,
    usernamePassword: "user15:pass15",
  },
  {
    id: "16",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-09-30",
    isExpired: false,
    usernamePassword: "user16:pass16",
  },
  {
    id: "17",
    renew: false,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "9090",
    expiredData: "2025-02-15",
    isExpired: true,
    usernamePassword: "user17:pass17",
  },
  {
    id: "18",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "7070",
    expiredData: "2024-11-10",
    isExpired: false,
    usernamePassword: "user18:pass18",
  },
  {
    id: "19",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "6060",
    expiredData: "2024-10-25",
    isExpired: false,
    usernamePassword: "user19:pass19",
  },
  {
    id: "20",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-30",
    isExpired: true,
    usernamePassword: "user20:pass20",
  },
  {
    id: "21",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2025-05-10",
    isExpired: false,
    usernamePassword: "user21:pass21",
  },
  {
    id: "22",
    renew: false,
    status: false,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-12-20",
    isExpired: true,
    usernamePassword: "user22:pass22",
  },
  {
    id: "23",
    renew: true,
    status: true,
    package: "Basic",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "2020",
    expiredData: "2024-09-05",
    isExpired: false,
    usernamePassword: "user23:pass23",
  },
  {
    id: "24",
    renew: true,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-11-21",
    isExpired: true,
    usernamePassword: "user24:pass24",
  },
  {
    id: "25",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "9090",
    expiredData: "2025-06-01",
    isExpired: false,
    usernamePassword: "user25:pass25",
  },
  {
    id: "26",
    renew: false,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "7070",
    expiredData: "2024-10-11",
    isExpired: false,
    usernamePassword: "user26:pass26",
  },
  {
    id: "27",
    renew: true,
    status: false,
    package: "Basic",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2024-11-15",
    isExpired: true,
    usernamePassword: "user27:pass27",
  },
  {
    id: "28",
    renew: false,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "5050",
    expiredData: "2025-03-01",
    isExpired: false,
    usernamePassword: "user28:pass28",
  },
  {
    id: "29",
    renew: true,
    status: false,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "4040",
    expiredData: "2024-10-30",
    isExpired: false,
    usernamePassword: "user29:pass29",
  },
  {
    id: "30",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "3030",
    expiredData: "2024-12-10",
    isExpired: true,
    usernamePassword: "user30:pass30",
  },
] as const;

export const proxiesData = [
  {
    title: "My Active Proxies",
    content: "12 Proxies",
    fill: "success",
    theme: "success",
    icon: Zap,
  },
  {
    title: "My Expired Proxies",
    content: "15 Proxies",
    fill: "alert",
    theme: "alert",
    icon: Zap,
  },
  {
    title: "All Proxies",
    content: "27 Proxies",
    fill: "secondary",
    theme: "secondary",
    icon: Zap,
  },
] as const;

export const proxiesTableData = [
  {
    id: "1",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "8080",
    expiredData: "2024-12-01",
    isExpired: false,
    usernamePassword: "user1:pass1",
  },
  {
    id: "2",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Yearly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-08-01",
    isExpired: true,
    usernamePassword: "user2:pass2",
  },
  {
    id: "3",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Weekly",
    type: "Residential",
    network: "3G",
    port: "7070",
    expiredData: "2024-09-15",
    isExpired: false,
    usernamePassword: "user3:pass3",
  },
  {
    id: "4",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-01-20",
    isExpired: false,
    usernamePassword: "user4:pass4",
  },
  {
    id: "5",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-01",
    isExpired: false,
    usernamePassword: "user5:pass5",
  },
  {
    id: "6",
    renew: true,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "5050",
    expiredData: "2025-05-01",
    isExpired: false,
    usernamePassword: "user6:pass6",
  },
  {
    id: "7",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-09-21",
    isExpired: true,
    usernamePassword: "user7:pass7",
  },
  {
    id: "8",
    renew: false,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "3G",
    port: "2020",
    expiredData: "2024-11-01",
    isExpired: true,
    usernamePassword: "user8:pass8",
  },
  {
    id: "9",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "4G",
    port: "9090",
    expiredData: "2024-12-15",
    isExpired: false,
    usernamePassword: "user9:pass9",
  },
  {
    id: "10",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Monthly",
    type: "Residential",
    network: "5G",
    port: "7070",
    expiredData: "2024-10-05",
    isExpired: true,
    usernamePassword: "user10:pass10",
  },
  {
    id: "11",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2025-04-01",
    isExpired: false,
    usernamePassword: "user11:pass11",
  },
  {
    id: "12",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2024-10-15",
    isExpired: false,
    usernamePassword: "user12:pass12",
  },
  {
    id: "13",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-21",
    isExpired: false,
    usernamePassword: "user13:pass13",
  },
  {
    id: "14",
    renew: false,
    status: false,
    package: "Basic",
    plan: "Yearly",
    type: "Residential",
    network: "3G",
    port: "3030",
    expiredData: "2025-06-01",
    isExpired: true,
    usernamePassword: "user14:pass14",
  },
  {
    id: "15",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "2020",
    expiredData: "2024-12-05",
    isExpired: false,
    usernamePassword: "user15:pass15",
  },
  {
    id: "16",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-09-30",
    isExpired: false,
    usernamePassword: "user16:pass16",
  },
  {
    id: "17",
    renew: false,
    status: false,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "5G",
    port: "9090",
    expiredData: "2025-02-15",
    isExpired: true,
    usernamePassword: "user17:pass17",
  },
  {
    id: "18",
    renew: true,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "7070",
    expiredData: "2024-11-10",
    isExpired: false,
    usernamePassword: "user18:pass18",
  },
  {
    id: "19",
    renew: true,
    status: true,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "4G",
    port: "6060",
    expiredData: "2024-10-25",
    isExpired: false,
    usernamePassword: "user19:pass19",
  },
  {
    id: "20",
    renew: false,
    status: true,
    package: "Basic",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "5050",
    expiredData: "2024-11-30",
    isExpired: true,
    usernamePassword: "user20:pass20",
  },
  {
    id: "21",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "4040",
    expiredData: "2025-05-10",
    isExpired: false,
    usernamePassword: "user21:pass21",
  },
  {
    id: "22",
    renew: false,
    status: false,
    package: "Enterprise",
    plan: "Monthly",
    type: "Datacenter",
    network: "5G",
    port: "3030",
    expiredData: "2024-12-20",
    isExpired: true,
    usernamePassword: "user22:pass22",
  },
  {
    id: "23",
    renew: true,
    status: true,
    package: "Basic",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "2020",
    expiredData: "2024-09-05",
    isExpired: false,
    usernamePassword: "user23:pass23",
  },
  {
    id: "24",
    renew: true,
    status: false,
    package: "Premium",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "8080",
    expiredData: "2024-11-21",
    isExpired: true,
    usernamePassword: "user24:pass24",
  },
  {
    id: "25",
    renew: true,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Datacenter",
    network: "5G",
    port: "9090",
    expiredData: "2025-06-01",
    isExpired: false,
    usernamePassword: "user25:pass25",
  },
  {
    id: "26",
    renew: false,
    status: true,
    package: "Enterprise",
    plan: "Monthly",
    type: "Residential",
    network: "4G",
    port: "7070",
    expiredData: "2024-10-11",
    isExpired: false,
    usernamePassword: "user26:pass26",
  },
  {
    id: "27",
    renew: true,
    status: false,
    package: "Basic",
    plan: "Weekly",
    type: "Datacenter",
    network: "5G",
    port: "6060",
    expiredData: "2024-11-15",
    isExpired: true,
    usernamePassword: "user27:pass27",
  },
  {
    id: "28",
    renew: false,
    status: true,
    package: "Standard",
    plan: "Yearly",
    type: "Residential",
    network: "4G",
    port: "5050",
    expiredData: "2025-03-01",
    isExpired: false,
    usernamePassword: "user28:pass28",
  },
  {
    id: "29",
    renew: true,
    status: false,
    package: "Enterprise",
    plan: "Weekly",
    type: "Residential",
    network: "5G",
    port: "4040",
    expiredData: "2024-10-30",
    isExpired: false,
    usernamePassword: "user29:pass29",
  },
  {
    id: "30",
    renew: false,
    status: true,
    package: "Premium",
    plan: "Monthly",
    type: "Datacenter",
    network: "3G",
    port: "3030",
    expiredData: "2024-12-10",
    isExpired: true,
    usernamePassword: "user30:pass30",
  },
] as const;

export const depositsData = [
  {
    title: "This Month",
    price: "15.00$",
    color: "#26a6a4",
    data: [
      { id: 1, amount: 20 },
      { id: 2, amount: 30 },
      { id: 3, amount: 70 },
      { id: 4, amount: 45 },
      { id: 5, amount: 50 },
    ],
  },
  {
    title: "This Year",
    price: "125.00$",
    color: "#f63d68",
    data: [
      { id: 1, amount: 150 },
      { id: 2, amount: 320 },
      { id: 3, amount: 710 },
      { id: 4, amount: 415 },
      { id: 5, amount: 820 },
    ],
  },
  {
    title: "All Time",
    price: "500.00$",
    color: "#7a5af8",
    data: [
      { id: 1, amount: 2000 },
      { id: 2, amount: 3012 },
      { id: 3, amount: 7460 },
      { id: 4, amount: 4512 },
      { id: 5, amount: 8046 },
    ],
  },
] as const;

export const depositsTableData = [
  {
    id: 1,
    amount: "25.00 USDT",
    date: "Jan 4, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 2,
    amount: "50.00 USDT",
    date: "Jan 4, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 3,
    amount: "120.00 USDT",
    date: "Jan 2, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 4,
    amount: "125.00 USDT",
    date: "Jan 6, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 5,
    amount: "130.00 USDT",
    date: "Jan 8, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 6,
    amount: "75.00 USDT",
    date: "Jan 6, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 7,
    amount: "500.00 USDT",
    date: "Jan 4, 2022",
    typeOfPayment: "Payeer",
  },

  {
    id: 8,
    amount: "60.00 USDT",
    date: "Feb 1, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 9,
    amount: "110.00 USDT",
    date: "Feb 2, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 10,
    amount: "95.00 USDT",
    date: "Feb 5, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 11,
    amount: "200.00 USDT",
    date: "Feb 6, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 12,
    amount: "175.00 USDT",
    date: "Feb 8, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 13,
    amount: "80.00 USDT",
    date: "Feb 10, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 14,
    amount: "400.00 USDT",
    date: "Feb 14, 2022",
    typeOfPayment: "Crypto",
  },

  {
    id: 15,
    amount: "300.00 USDT",
    date: "Mar 1, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 16,
    amount: "250.00 USDT",
    date: "Mar 3, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 17,
    amount: "150.00 USDT",
    date: "Mar 5, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 18,
    amount: "450.00 USDT",
    date: "Mar 6, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 19,
    amount: "225.00 USDT",
    date: "Mar 8, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 20,
    amount: "135.00 USDT",
    date: "Mar 10, 2022",
    typeOfPayment: "Payeer",
  },

  {
    id: 21,
    amount: "500.00 USDT",
    date: "Apr 1, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 22,
    amount: "600.00 USDT",
    date: "Apr 2, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 23,
    amount: "350.00 USDT",
    date: "Apr 5, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 24,
    amount: "750.00 USDT",
    date: "Apr 6, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 25,
    amount: "275.00 USDT",
    date: "Apr 8, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 26,
    amount: "150.00 USDT",
    date: "Apr 10, 2022",
    typeOfPayment: "Payeer",
  },

  {
    id: 27,
    amount: "450.00 USDT",
    date: "May 1, 2022",
    typeOfPayment: "Crypto",
  },
  {
    id: 28,
    amount: "300.00 USDT",
    date: "May 2, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 29,
    amount: "225.00 USDT",
    date: "May 5, 2022",
    typeOfPayment: "Payeer",
  },
  {
    id: 30,
    amount: "700.00 USDT",
    date: "May 6, 2022",
    typeOfPayment: "Crypto",
  },
] as const;

export const plansData = ["Basic", "Standard", "Premium"] as const;

export const durationsData = ["Hourly", "Monthly", "Yearly"] as const;

export const pricingPlanData = {
  Basic: {
    Hourly: [
      {
        id: 1,
        name: "2 Hours/Basic plan",
        description: "talk about your offer here.",
        price: "2.00$",
      },
      {
        id: 2,
        name: "4 Hours/Basic plan",
        description: "talk about your offer here.",
        price: "3.50$",
      },
      {
        id: 3,
        name: "6 Hours/Basic plan",
        description: "talk about your offer here.",
        price: "5.00$",
      },
      {
        id: 4,
        name: "8 Hours/Basic plan",
        description: "talk about your offer here.",
        price: "6.50$",
      },
    ],
    Monthly: [
      {
        id: 5,
        name: "1 Month/Basic plan",
        description: "talk about your offer here.",
        price: "30.00$",
      },
      {
        id: 6,
        name: "3 Months/Basic plan",
        description: "talk about your offer here.",
        price: "80.00$",
      },
      {
        id: 7,
        name: "6 Months/Basic plan",
        description: "talk about your offer here.",
        price: "150.00$",
      },
      {
        id: 8,
        name: "12 Months/Basic plan",
        description: "talk about your offer here.",
        price: "280.00$",
      },
    ],
    Yearly: [
      {
        id: 9,
        name: "1 Year/Basic plan",
        description: "talk about your offer here.",
        price: "300.00$",
      },
      {
        id: 10,
        name: "2 Years/Basic plan",
        description: "talk about your offer here.",
        price: "580.00$",
      },
    ],
  },
  Standard: {
    Hourly: [
      {
        id: 11,
        name: "2 Hours/Standard plan",
        description: "talk about your offer here.",
        price: "3.00$",
      },
      {
        id: 12,
        name: "4 Hours/Standard plan",
        description: "talk about your offer here.",
        price: "5.50$",
      },
      {
        id: 13,
        name: "6 Hours/Standard plan",
        description: "talk about your offer here.",
        price: "7.50$",
      },
      {
        id: 14,
        name: "8 Hours/Standard plan",
        description: "talk about your offer here.",
        price: "9.00$",
      },
    ],
    Monthly: [
      {
        id: 15,
        name: "1 Month/Standard plan",
        description: "talk about your offer here.",
        price: "50.00$",
      },
      {
        id: 16,
        name: "3 Months/Standard plan",
        description: "talk about your offer here.",
        price: "140.00$",
      },
      {
        id: 17,
        name: "6 Months/Standard plan",
        description: "talk about your offer here.",
        price: "270.00$",
      },
      {
        id: 18,
        name: "12 Months/Standard plan",
        description: "talk about your offer here.",
        price: "500.00$",
      },
    ],
    Yearly: [
      {
        id: 19,
        name: "1 Year/Standard plan",
        description: "talk about your offer here.",
        price: "500.00$",
      },
      {
        id: 20,
        name: "2 Years/Standard plan",
        description: "talk about your offer here.",
        price: "950.00$",
      },
    ],
  },
  Premium: {
    Hourly: [
      {
        id: 21,
        name: "2 Hours/Premium plan",
        description: "talk about your offer here.",
        price: "5.00$",
      },
      {
        id: 22,
        name: "4 Hours/Premium plan",
        description: "talk about your offer here.",
        price: "9.50$",
      },
      {
        id: 23,
        name: "6 Hours/Premium plan",
        description: "talk about your offer here.",
        price: "12.50$",
      },
      {
        id: 24,
        name: "8 Hours/Premium plan",
        description: "talk about your offer here.",
        price: "16.00$",
      },
    ],
    Monthly: [
      {
        id: 25,
        name: "1 Month/Premium plan",
        description: "talk about your offer here.",
        price: "90.00$",
      },
      {
        id: 26,
        name: "3 Months/Premium plan",
        description: "talk about your offer here.",
        price: "250.00$",
      },
      {
        id: 27,
        name: "6 Months/Premium plan",
        description: "talk about your offer here.",
        price: "450.00$",
      },
      {
        id: 28,
        name: "12 Months/Premium plan",
        description: "talk about your offer here.",
        price: "800.00$",
      },
    ],
    Yearly: [
      {
        id: 29,
        name: "1 Year/Premium plan",
        description: "talk about your offer here.",
        price: "800.00$",
      },
      {
        id: 30,
        name: "2 Years/Premium plan",
        description: "talk about your offer here.",
        price: "1500.00$",
      },
    ],
  },
} as const;
