const NAME_PROJECT = "PORTIA";
const NAME_SECRET = "NEXT_CWS";

export const TOKEN_KEY = `${NAME_SECRET}_${NAME_PROJECT}_TOKEN`;
export const EMAIL_KEY = `${NAME_SECRET}_${NAME_PROJECT}_EMAIL`;
export const USER_KEY = `${NAME_SECRET}_${NAME_PROJECT}_USER`;
