import { useResponse } from "./shared/use-response";
import {
  useGetAllFaqs,
  useGetFaqs,
  useGetFeaturesOffers,
  useGetOffers,
  useGetReviews,
  useSendContactMessage,
} from "./root";

import {
  useLogin,
  useRegister,
  useLogout,
  useLoginWithGoogle,
  useSendResetEmail,
  useSetNewPassword,
  useVerifyCode,
  useResendVerificationCode,
} from "./auth";

import {
  useAddProxy,
  useEditAuthProxy,
  useEditInfoProxy,
  useFixProxy,
  useGetActiveProxies,
  useGetDepositsHistories,
  useGetAffiliateHistories,
  useGetAffiliateStatistics,
  useGetDepositsStatistics,
  useGetAllPackages,
  useGetCostPlans,
  useGetInactiveProxies,
  useGetPorts,
  useGetPricingPlans,
  useGetProxiesCounts,
  useGetProxyCities,
  useGetProxyCountries,
  useGetProxyIpRotations,
  useGetProxyLocations,
  useGetProxyServiceProvider,
  useGetUserBalance,
  useGetUserDetails,
  useUpdateUserProfile,
} from "./dashboard";
export {
  useResponse,
  useGetAllFaqs,
  useGetFaqs,
  useGetFeaturesOffers,
  useGetOffers,
  useGetReviews,
  useSendContactMessage,
  useLogin,
  useRegister,
  useLogout,
  useLoginWithGoogle,
  useSendResetEmail,
  useSetNewPassword,
  useVerifyCode,
  useResendVerificationCode,
  useAddProxy,
  useEditAuthProxy,
  useEditInfoProxy,
  useFixProxy,
  useGetActiveProxies,
  useGetDepositsHistories,
  useGetAffiliateHistories,
  useGetAffiliateStatistics,
  useGetDepositsStatistics,
  useGetAllPackages,
  useGetCostPlans,
  useGetInactiveProxies,
  useGetPorts,
  useGetPricingPlans,
  useGetProxiesCounts,
  useGetProxyCities,
  useGetProxyCountries,
  useGetProxyIpRotations,
  useGetProxyLocations,
  useGetProxyServiceProvider,
  useGetUserBalance,
  useGetUserDetails,
  useUpdateUserProfile,
};
