import { useResponse } from "./shared/use-response";

import {
  useLogin,
  useRegister,
  useLogout,
  useLoginWithGoogle,
  useSendResetEmail,
  useSetNewPassword,
  useVerifyCode,
  useResendVerificationCode,
} from "./auth";

import { useRenewProxy } from "./dashboard/proxy/use-renew-proxy";

import {
  useAddProxy,
  useEditAuthProxy,
  useEditInfoProxy,
  useFixProxy,
  useGetActiveProxies,
  useGetDepositsHistories,
  useGetAffiliateHistories,
  useGetAffiliateStatistics,
  useGetDepositsStatistics,
  useGetAllPackages,
  useGetCostPlans,
  useGetInactiveProxies,
  useGetPorts,
  useGetPricingPlans,
  useGetProxiesCounts,
  useGetProxyCities,
  useGetProxyCountries,
  useGetProxyIpRotations,
  useGetProxyLocations,
  useGetProxyServiceProvider,
  useGetUserBalance,
  useGetUserDetails,
  useUpdateUserProfile,
  useExportData,
  useGetTablesData,
  useGetOffersPackage,
  useGetPackageWithPlans,
  useGetProxyById,
} from "./dashboard";
export {
  useResponse,
  useLogin,
  useRegister,
  useLogout,
  useLoginWithGoogle,
  useSendResetEmail,
  useSetNewPassword,
  useVerifyCode,
  useResendVerificationCode,
  useAddProxy,
  useEditAuthProxy,
  useEditInfoProxy,
  useFixProxy,
  useGetActiveProxies,
  useGetDepositsHistories,
  useGetAffiliateHistories,
  useGetAffiliateStatistics,
  useGetDepositsStatistics,
  useGetAllPackages,
  useGetCostPlans,
  useGetInactiveProxies,
  useGetPorts,
  useGetPricingPlans,
  useGetProxiesCounts,
  useGetProxyCities,
  useGetProxyCountries,
  useGetProxyIpRotations,
  useGetProxyLocations,
  useGetProxyServiceProvider,
  useGetUserBalance,
  useGetUserDetails,
  useUpdateUserProfile,
  useExportData,
  useGetTablesData,
  useGetOffersPackage,
  useGetPackageWithPlans,
  useGetProxyById,
  useRenewProxy,
};
