import { login } from "./auth/login";
import { register } from "./auth/register";
import { logout } from "./auth/logout";
import { verificationCode } from "./auth/verification-code";
import { resendVerificationCode } from "./auth/resend-verification-code";
import { setNewPassword } from "./auth/set-new-password";
import { sendResetEmail } from "./auth/send-reset-email";
import { loginWithGoogle } from "./auth/login-with-google";

import {
  getAffiliateHistories,
  getAffiliateStatistics,
  getDepositHistories,
  getDepositStatistics,
  getProxyCities,
  getProxyCountries,
  getProxyIpRotations,
  getProxyLocations,
  getProxyServiceProviders,
  getActiveProxies,
  getInactiveProxies,
  getProxiesCounts,
  addProxy,
  fixProxy,
  editAuthProxy,
  editInfoProxy,
  getPricingPlans,
  getAllPackages,
  getCostPlans,
  getPorts,
  updateUserProfile,
  getUserBalance,
  getUserDetails,
  getTablesData,
  exportData,
  getOffersPackage,
  getPackageWithPlans,
  getProxyById,
} from "./dashboard";
import {
  getFaqs,
  getAllFaqs,
  getReviews,
  getFeaturesOffer,
  getOffers,
  sendContactMessage,
  getPlansOffer,
} from "./root";

export {
  login,
  register,
  loginWithGoogle,
  logout,
  sendResetEmail,
  setNewPassword,
  verificationCode,
  resendVerificationCode,
  getAffiliateHistories,
  getAffiliateStatistics,
  getDepositHistories,
  getDepositStatistics,
  getProxyCities,
  getProxyCountries,
  getProxyIpRotations,
  getProxyLocations,
  getProxyServiceProviders,
  getActiveProxies,
  getInactiveProxies,
  getProxiesCounts,
  getPlansOffer,
  addProxy,
  fixProxy,
  editAuthProxy,
  editInfoProxy,
  getPricingPlans,
  getAllPackages,
  getCostPlans,
  getPorts,
  getFaqs,
  getAllFaqs,
  getReviews,
  getFeaturesOffer,
  getOffers,
  sendContactMessage,
  updateUserProfile,
  getUserBalance,
  getUserDetails,
  getTablesData,
  exportData,
  getOffersPackage,
  getPackageWithPlans,
  getProxyById,
};
